### ISSUE TITLE
Structural pattern matching added starting from Python 3.10

### ISSUE THREAD

**Issue by hfmuzb** [learning-zone/python-basics#13]
Starting 3.10 version, structural pattern matching is added to Python: 
https://docs.python.org/3/whatsnew/3.10.html#pep-634-structural-pattern-matching 

answer to the following question needs to be updated: 
https://github.com/learning-zone/python-basics#q-does-python-have-a-switch-case-statement

**Comment by PipeKnight** [comment]
Yea, man, this repo is totally outdated, I suggest everyone not to use it. Asking something regarding Python 2 in 2023 is madness. Okay, maybe you have some legacy project, and you need someone who really knows all these things, but for a regular Python job this is absolute nonsense!

**Comment by learning-zone** [comment]
> Yea, man, this repo is totally outdated, I suggest everyone not to use it. Asking something regarding Python 2 in 2023 is madness. Okay, maybe you have some legacy project, and you need someone who really knows all these things, but for a regular Python job this is absolute nonsense!

Can you raise a PR for this?

**Comment by TopCoder2K** [comment]
@learning-zone, README.md hasn't been updated... Kindly remind you about this issue.

**Comment by learning-zone** [comment]
Can you raise a PR for this change?
